def find_character(name, story_bible):
    """Looks through main, side, and passing characters for a name match."""
    all_characters = (
        story_bible["characters"]["main"]
        + story_bible["characters"]["side"]
        + story_bible["characters"]["passing"]
    )
    for character in all_characters:
        if character.get("name") == name:
            return character
    return None


def find_region(name, story_bible):
    """Looks through the world's regions for a name match."""
    for region in story_bible["world"]["regions"]:
        if region.get("name") == name:
            return region
    return None


def find_memory(text, story_bible):
    """Looks through the Story Bible's memory list for a matching entry."""
    for memory_entry in story_bible["memory"]:
        if text.lower() in str(memory_entry).lower():
            return memory_entry
    return None


def find_plot_thread(text, story_bible):
    """Looks through active plot threads for a matching entry."""
    for thread in story_bible["plot_threads"]["active"]:
        if text.lower() in str(thread).lower():
            return thread
    return None


def compose_context(scene_blueprint, story_bible):
    """
    Takes a Scene Blueprint dict and the full Story Bible, and returns a
    Context Package - only the pieces the Writing Agent actually needs
    for this one scene. Nothing here is generated by AI - it's all
    direct lookups.
    """

    context_package = {
        "characters": [],
        "missing_characters": [],
        "location": None,
        "world_rules": story_bible["world"]["world_rules"],
        "current_day": story_bible["timeline"]["current_day"],
        "memories": [],
        "missing_memories": [],
        "plot_threads": [],
        "missing_plot_threads": []
    }

    # Characters requested by the Scene Planner
    for name in scene_blueprint.get("characters", []):
        character = find_character(name, story_bible)
        if character:
            context_package["characters"].append(character)
        else:
            context_package["missing_characters"].append(name)

    # Location requested by the Scene Planner
    location_name = scene_blueprint.get("location")
    region = find_region(location_name, story_bible)
    if region:
        context_package["location"] = region
    else:
        context_package["location"] = {
            "name": location_name,
            "note": "not found in Story Bible yet"
        }

    # Memories requested by the Scene Planner
    for memory_text in scene_blueprint.get("required_memories", []):
        memory_entry = find_memory(memory_text, story_bible)
        if memory_entry:
            context_package["memories"].append(memory_entry)
        else:
            context_package["missing_memories"].append(memory_text)

    # Plot threads requested by the Scene Planner
    for thread_text in scene_blueprint.get("required_plot_threads", []):
        thread_entry = find_plot_thread(thread_text, story_bible)
        if thread_entry:
            context_package["plot_threads"].append(thread_entry)
        else:
            context_package["missing_plot_threads"].append(thread_text)

    return context_package
